try {
    hello();
} catch (e) {
    console.log(e);
};

try {
    anotherFunction();
} catch {
    console.log("Esto es un error")
};